ircv3/ircv3-specifications

index
I hope I put it into correct spot following alphabetical order.
=> index: add Limnoria as IRCv3.1 compliant bot

index
SASL was supported in [IB 1.3](https://bugzilla.mozilla.org/show_bug.cgi?id=955004)/[TB 19](https://bugzilla.mozilla.org/show_bug.cgi?id=812921)
NAMESX/multi-prefix was supported in [IB 1.4](https://bugzilla.mozilla.org/show_bug.cgi?id=955179)/[TB 21](https://bugzilla.mozilla.org/show_bug.cgi?id=842183)
Please let me know if you have any questions as I'm the [official owner of the IRC code](https://wiki.mozilla.org/Modules/Chat) in both these products (additionally @aleth is a peer). I wasn't sure whether to list Mozilla as a [participant](https://github.com/ircv3/ircv3-specifications/blob/434239790c9a5764c3d68cde99c6ddb007f5cbbe/index#L15) or not, is there a process for that or...?
Thanks!
=> Add Instantbird and Thunderbird to the list of v3.1 Compliant Software

specification/monitor-3.2.md
This pull request explains the rationale for deprecating `WATCH` with `MONITOR` by explaining the goals that `MONITOR` seeks to resolve with `WATCH`.
Closes #49.
=> monitor: explain `MONITOR` vs `WATCH` (closes #49)

specification/capability-negotiation-3.2.md
There are no known capabilities which use ack-required (~).
Further, it appears that many clients do not properly support the sticky (=) capability modifier,
and in reality, we're required to enforce it with a NAK anyway.  So we just codify the status quo
behaviour to allow clients and servers to drop support for ack-required capabilities and relax the
behaviour of sticky capabilities.
=> [3.2] cap: deprecate sticky (=) and ack-required (~) capability modifiers

extensions/server-time-3.2.md
Trivial change. This is how all the other specs do it.
=> server-time-3.2: Fix ircv3.atheme.org links to be relative

extensions/echo-message-3.2.md, index
This pull request provides a modified `echo-message` capability for 3.2.  The modification removes the example which takes advantage of 3.3's labeled replies proposal.
Closes #100, #135.
=> Modified echo-message for 3.2

specification/metadata-3.2.md
Just implements the changes in #130, makes the error name and string more sensible with the new rewrite of `METADATA`.
=> Fixes and updates for METADATA spec

CNAME
Just removes the CNAME file in here, so the website works properly.
=> website: remove CNAME file for website

core/capability-negotiation-3.1.md, core/capability-negotiation-3.2.md, core/message-intents-3.3.md, core/message-tags-3.2.md, core/metadata-3.2.md, core/monitor-3.2.md, documentation/sasl-dh-aes.md, documentation/sasl-dh-blowfish.md, extensions/account-notify-3.1.md, extensions/account-tag-3.2.md, extensions/away-notify-3.1.md, extensions/batch-3.2.md, extensions/batch/netsplit.md, extensions/cap-notify-3.2.md, extensions/chghost-3.2.md, extensions/echo-message-3.2.md, extensions/extended-join-3.1.md, extensions/invite-notify-3.2.md, extensions/multi-prefix-3.1.md, extensions/sasl-3.1.md, extensions/sasl-3.2.md, extensions/server-time-3.2.md, extensions/tls-3.1.md, extensions/userhost-in-names-3.2.md
This moves the copyright data to YAML front matter so that it is parseable.  There is a companion commit in ircv3/ircv3.github.io#1 which makes use of this data.
This also adds copyright data where it was missing based on git logs.
=> Copyright metadata

core/capability-negotiation-3.2.md, extensions/batch-3.2.md, extensions/cap-notify-3.2.md, extensions/extended-join-3.1.md, extensions/sasl-3.1.md, extensions/sasl-3.2.md, extensions/server-time-3.2.md
This commit also fixes a couple links that weren't corrected prior to the site going live.
=> Rework links to be relative rather than absolute.

extensions/extended-join-3.1.md
Just a small formatting bug with the extended-join spec.
=> Remove duplicated header in extended-join spec

core/message-tags-3.2.md
Markdown parsed it as if it were another plaintext line of the third
list item. Keeping it after the list and using six spaces could have
worked too, but this is clearer imo.
Also uses tabs just like the other code blocks, for consistency.
------
Before:
After:
=> message-tags-3.2: move example to fix code block formatting

extensions/account-notify-3.1.md
WHO after netsplit is unnecessary in the context of account-notify. All the rejoins after netsplit will include the relevant account information in extended-join.
=> Remove WHOX on netsplit advice

core/message-tags-3.2.md
As it's currently written, two different tags with the same key are allowed.
=> Fix formulation of tags uniqueness

extensions/cap-notify-3.2.md
1. To make it consistent with CAP LS, and even possible to implement at all.
2. Examples already correctly have the nick between CAP and NEW.
=> Fix cap-notify spec to mention nick.

extensions/cap-notify-3.2.md
Current spec doesn't say either "yes" or "no".
Probably this change is too big though, and should go to 3.3?
=> Specify that CAP NEW can have values, similar to CAP LS.

core/capability-negotiation-3.1.md
The wording of the format might not be the most clear.
=> Add example of ERR_INVALIDCAPCMD

extensions/batch-3.2.md, extensions/batch/netsplit-3.2.md
Other examples of batch already use lower case with vendor-specific
types.
=> Make batch types lower case, as are capability names and tag names.

core/capability-negotiation-3.1.md, core/message-tags-3.2.md
Apparently the existing warnings were not strong enough. Added a bigger one to attempt to fix that.
=> Add a warning about name collision in capabilities and tags.

core/monitor-3.2.md
issue #80 change the wording of target to dissalow hostmasks.
This was to avoid ircd's having to do wildcard matching on every
client registration, but broke the definition of RPL_MONONLINE.
Current implementations send a hostmask with RPL_MONONLINE, the
spec should match that to avoid incompatibilities
=> RPL_MONONLINE should include user@host

extensions/sasl-3.1.md
Just a quick patch. Fixes the website HTML generation of the SASL 3.1 spec in preparation for https://github.com/ircv3/ircv3.github.io/pull/38
=> sasl-3.1: Wrap <mechanism> tag in inline-code backticks

core/sts-3.3.md
Added as core for 3.3, the idea is that this helps migrating from insecure connections to secure ones and paves the way for mandating secure connections for new features (if that ever happens).
The spec is trying to solve two problems at once, one is redirecting clients to a TLS port and the enforcement of it for all future connections. This is different to HSTS because browsers can be redirected to a secure site while there is no standardized way to do the equivalent for IRC clients.
=> Add Strict Transport Security specification

core/metadata-3.2.md
```
2015-12-14 05:59:43      sim642 My problem is the 766 numeric's format defined in metadata-3.2
2015-12-14 05:59:58      sim642 the numerics section has no <Target> argument for the reply
2015-12-14 06:00:10      ElementAlchemist       OK, yes, so I implemented it strictly as defined in the spec
2015-12-14 06:00:11      sim642 below in the examples, a target is being used with the same numeric
2015-12-14 06:00:45      sim642 it feels a lot like 766 should have a <Target>
2015-12-14 06:00:52      sim642 because otherwise the reply seems kind of... pointless
2015-12-14 06:01:16      sim642 it just tells you that there wasn't the key you wanted, in a target it doesn't specify
2015-12-14 06:01:20      ElementAlchemist       ... the examples look really inconsistent actually
2015-12-14 …
```
=> metadata-3.2: Fix 766 numeric spec to match examples

core/metadata-3.2.md
This looks like it was just a typo/oversight, as I'm fairly sure being able to notify clients about keys that have been removed is desired. [mammon](https://github.com/mammon-ircd/mammon) actually already implements the `METADATA` event as shown here, sending out an event without the `<Value>` param on removed keys.
Pointed out by @sim642
=> metadata-3.2: Fix METADATA event to allow notification of removed keys

core/metadata-3.2.md
- Clarify that only ERR_KEYINVALID is sent in reply when the key name is invalid.
- Clarify that the RPL_KEYVALUE and RPL_METADATAEND should only be sent for successful requests (either those numerics or one error numeric must be the reply).
=> metadata-3.2: Clarify METADATA SET

extensions/sasl-3.2.md
This changes SASL reauth from a MUST to a SHOULD. We want to encourage reauth where possible, but where it's not either for policy or technical reasons, servers can send `ERR_SASLALREADY` to let the client know it's not supported.
Most of the language in this PR comes from #203.
=> sasl-3.2: Change SASL reauth to a SHOULD

core/message-intents-3.3.md, core/sni-3.3.md, core/sts-3.3.md, documentation/sasl-dh-aes.md, documentation/sasl-dh-blowfish.md
This adds the `wip` and `deprecated` flags to specifications as I suggested in #216. This should make it more obvious to those who stumble on the raw Markdown files, as well as making it more intuitive and giving us more flexibility on the website (and closing https://github.com/ircv3/ircv3.github.io/issues/50 ).
=> formatting: Mark WiP and deprecated specifications in the markdown

core/capability-negotiation-3.1.md
If this is the desired behaviour from servers, I think it's is fairly non-obvious from reading the specification. This tries to make it more clear by specifying it directly in the `CAP REQ` section of the spec, for when people are implementing that subcommand.
=> cap-3.1: clarify that caps can be re-requested

core/capability-negotiation-3.2.md
For ```CAP LS 302```, clarify that ```<name>[=<value>]``` only apply to ```CAP LS``` and ```CAP NEW``` replies.
For example, this is valid:
```
Server: CAP * LS :sasl=EXTERNAL,FOO,PLAIN batch cap-notify
Client: CAP REQ :sasl
Server: CAP modernclient ACK :sasl
```
While this is **not** valid:
```
Server: CAP * LS :sasl=EXTERNAL,FOO,PLAIN batch cap-notify
Client: CAP REQ :sasl
Server: CAP modernclient ACK :sasl=EXTERNAL,FOO,PLAIN
```
This simplifies logic for clients by ensuring new values don't need parsed and tracked in ```CAP ACK``` and ```CAP NAK``` replies.
=> Clarify where cap values may be shown

core/capability-negotiation-3.1.md
For ```CAP LS```, clarify that servers which support negotiation but do not have any available capabilities must send an empty parameter in reply.  This matches the behavior of ```CAP LIST```.
For example:
```
Client: CAP LS
Server: CAP * LS :
```
Without this, clients have no way to determine that they should send ```CAP END``` to continue nick registration.
=> Clarify CAP LS reply for when no caps available

core/message-tags-3.3.md
This specification adds a new capability for general message tags support and
a prefix for expressing client-to-client tags.
This PR replaces #236
=> IRCv3.3 Message Tags

core/sts-3.3.md
This addresses the irc.kde.org -> irc.freenode.net CNAME case.
Also, remove TODOs:
* This commit covers the motivation for advertising hosts the server has a valid certificate for.
* #266 covers the motivation the the `sub` key
* SNI is now a formal recommendation: https://github.com/ircv3/ircv3-specifications/blob/7d6f6a4/core/sni-3.3.md
=> STS: Add DoS example for untrusted 3rd party DNS aliases

core/message-tags-3.3.md
* Clarify that servers advertising the CAP understand all client-initiated tags, prefixed or otherwise.
* Server-initiated tags take precedence over client-only tags
* pseudo-BNF whitespace
* Security note about unprefixed client-initiated tags
* More/improved examples
=> Message tags 3.3 clarifications

core/capability-negotiation-3.1.md, core/message-tags-3.2.md, extensions/batch-3.2.md
Mentioned in IRC with projects implementing draft support for specs with names like `draft/client-tags` and such, and subsequently some clients having issues with names like that since they were looking at parsing out and validating vendor prefixes.
It makes much sense to just make sure clients treat them as opaque identifiers, makes clients more resilient and leaves it open for further future clarification/expansion.
=> cap/tags: Specify that idents are to be parsed as opaque identifiers

core/metadata-3.2.md
We already practically don't recommend implementing it right now due to issues being solved in 3.3 (see various issues/PRs on this repo for more context here).
The IRCv3 version of metadata can include the basic metadata stuff and whatever new notify spec we have, so that we have one document we can point people towards to implement it. Right now, having this displayed as a regular, recommended spec on our site does more harm than good I feel.
=> Deprecate metadata-3.2 for the time being.

core/labeled-replies-3.3.md
=> Add spec for labeled-replies.

extensions/sasl-3.1.md
The specification mentions:
> The client can abort an authentication by sending an asterisk as the data. The server will send a 904 numeric.
However later we say this returns 906 numeric:
> `906` aka `ERR_SASLABORTED` is sent when the SASL authentication is aborted because the client sent an `AUTHENTICATE` command with `*` as the parameter.
>
>     :server 906 <nick> :SASL authentication aborted
=> Fix SASL 3.1, aborted is 906 not 904

client-tags/reply.md
`+draft/reply=msgid`
Depends on #285
=> Reply client tag

core/message-tags-3.3.md
* Specs a TAGMSG tag-only event. Enables things like content-less reactions/faving, message deletion, message seen notifications (ircv3/ircv3-ideas#1)
* Increases the size limit for tags to 4096
* Cap name version bump to `draft/message-tags-0.2`
=> Add empty tag-only message support and an increased size limit for tags

client-tags/react.md
`+draft/react=👍`
Depends on ~#287~ and ~#288~
Source of inspiration:
https://slackhq.com/722-ways-to-say-i-got-your-message-e69a4d7da8e4#.fmzgegc5z
My UI implementation in IRCCloud:
=> Reaction client tag

core/capability-negotiation-3.1.md, core/capability-negotiation-3.2.md, core/message-tags-3.2.md, core/message-tags-3.3.md, example-spec.md, extensions/cap-notify-3.2.md, extensions/sasl-3.1.md, extensions/sasl-3.2.md
This lets us, in the website, link between specifications where appropriate and makes the discoverability of things like new versions and extensions to existing capabilities much easier to see.
=> Add meta status keys to header yaml

extensions/chghost-3.2.md
As noted on IRC this was a little unclear. These examples are small and make sure it's treated correctly, and as well just help general implementers of this spec make sure they're doing the right thing.
=> chghost: Add examples which make it clear ~ is a part of the username

core/sts-3.3.md
This is one way to check whether a server wishes to be included in preload lists. Another method, proposed by `e`  on IRC is to request a signature from a valid certificate when submitting servers to a preload list.
=> sts-3.3: Add the preload key

extensions/tls-3.1.md
Small nit. The line should read 'its parameter', not 'it's parameter'.
=> Grammar nit

core/message-tags-3.2.md
How to handle this was a question raised to me in email. I think this is the most appropriate way to handle this sort of case (since here, there's no actual `"Character"` as specified by the table, so nothing to output when it's unescaped).
It's an edge case, but it should help make implementations just a bit more compatible knowing how they should handle this specifically.
=> message-tags-3.2: Clarify how to handle lone backslashes

core/message-tags-3.3.md
This can be read as "messages that exceed 510 bytes", which may be
interpreted as a confusing reference to RFC1459 message limits.
=> message-tags-3.3: Make the limit on servers adding tag data easier to read

core/message-tags-3.3.md
Unless a tag is specified otherwise, this is a security flaw.
=> message-tags-3.3: Servers must remove tags without the client-only prefix by default

core/message-tags-3.3.md
Return the NEEDMOREPARAMS numeric if all tags are removed.
=> message-tags-3.3: Allow empty TAGMSG explicitly, clarify server removal of unknown tags

extensions/sts.md
This removes the draft/ prefix from STS. See #296 for details and requirements.
=> Ratify STS

extensions/echo-message-3.2.md
Currently it is not permissible to respond to a spam message with a fake echo-message response. This relaxes the MUST requirement to a SHOULD to allow for this.
Thanks to @Robby- for raising this issue with me.
=> Amend echo-message to allow better spam filtering.

extensions/batch-3.2.md
This is a small fix to add a link to the `chathistory` page onto the `batch` extension page.
=> Add `chathistory` to the list of batch types

client-tags/react.md, client-tags/reply.md, extensions/echo-message-3.2.md, extensions/message-ids.md, extensions/message-tags.md
This addresses comments from #297 #334 #335 #367 #370 
I've deliberately only added errata for stuff that would have applied to the 3.2 spec.
Edit: this also covers additional typos and comments raised below:
* Clarification around empty/missing tag values
* Clarification around dupe handling and validation of tag key names
* Draft tags
=> Message tags updates

extensions/setname.md
* Introduces a new `setname` capability
* Introduces a new bidirectional `SETNAME` command
Realnames have historically been immutable for a connection, which has
historically been accepted, as they were rarely used and usually not as present
in client UIs. Still, multiple IRCds have provided independent, non-standard
commands to update realnames.
Nowadays, multiple clients show realnames directly in chat, next to the nick
name, or use information from the realname to provide enhancements, such as
using emails in the realname to provide gravatar based avatars, leading to
higher demand for this functionality than ever.
=> SETNAME Spec

extensions/message-ids.md
I reckon we've shown this to be stable enough, we have a few server implementations and all. Should be right to ratify as-is it feels like?
=> Ratify Message IDs

client-tags/typing.md, extensions/labeled-response.md, extensions/server-time-3.2.md, extensions/webirc.md
Make sure all dependent specs link to the canonical merged relative URL for message tags.
=> Fix links to message-tags spec

extensions/labeled-response.md
This addresses:
* https://github.com/ircv3/ircv3-ideas/issues/37 allow ACK instead of empty batch
This specifies new behaviour so the draft CAP version is bumped to `draft/labeled-response-0.2`
This should be merged before #378 (ratification)
=> ACK command for empty labeled responses

extensions/message-ids.md
This makes using them in e.g. CHATHISTORY more robust.
=> [message-ids] Forbid SPACE/NUL/CRLF/leading-colon in message IDs

extensions/message-tags.md
This is a one word change but needs some discussion (and possibly needs expanding with a clarifying paragraph)
Following on from discussion in https://github.com/ircv3/ircv3-specifications/pull/373#pullrequestreview-209467284 (click `show resolved` to expand) and ircv3/ircv3-ideas#38 this proposal aims to enforce utf8 in at least one, relatively newly introduced section of the protocol.
This would allow us to assume an interoperable baseline for future tag specs, even if we can't for freeform text that has a long legacy of mixed encodings where the user is on their own to decide.
From an implementation point of view, I don't think this should present a major issue. Tags already need to be parsed separately from the rest of the message. For clients that handle multiple encodings, or do …
=> [message-tags] Specify that tag values are utf8

core/capability-negotiation.md
Clarifies some issues brought up with the CAP spec. Specifically, fixes #368 and #369, and adds some language along the lines of that suggested by jw in #359.
These clarifications should make CAP more future-proof and consistent.
I'm not quite happy with the _"approaching the 510 byte limit"_ fragment of text in particular, but will continue editing it up. If anyone has recommendations, open to 'em!
=> Cap Clarifications

extensions/setname.md
Unchecked means incomplete or an intent to implement has been expressed. The numbers indicate minimum requirements. Any others?
=> Ratify setname

extensions/webirc.md
There could potentially be a case when the IPv6 address of a client
begins with a colon (`:`), such as when testing. This could pose an
issue, as the colon symbol is used to denote that the next argument is
the last argument, and should treat all spaces after it as included in
that argument, which means that no further arguments can be passed. This
creates a problem because there is still another argument, `options`,
which needs to be parsed.
=> webirc: Fix bad handling of IPv6 addresses

extensions/multiline.md
A solution to multiline messages (#208) using client to server batches based on https://gist.github.com/jesopo/092866e52b40cda6f6205263d04dbcf9
---
Currently implemented and testable with the IRCCloud client and servers (prattle: teams, bnc, slack) and bitbot.
---
Client sending a mutliline batch
Client: BATCH +123 draft/multiline #channel
Client: @batch=123 PRIVMSG #channel hello
Client: @batch=123 privmsg #channel :how is<SPACE>
Client: @batch=123;draft/multiline-concat PRIVMSG #channel :everyone?
Client: BATCH -123
Server sending the same batch
Server: @msgid=xxx;account=account :n!u@h BATCH +123 draft/multiline #channel
Server: @batch=123 :n!u@h PRIVMSG #channel hello
Server: @batch=123 :n!u@h PRIVMSG #channel :how is<SPACE>
Server: @batch=123;draft/multiline-concat :n!u@h PRIVMSG …
=> [multiline] Multiline message batches

extensions/account-notify-3.1.md
This clarifies that account-notify should be sent to your own client when changing your own account name (via /nickserv set accountname or otherwise)
I don't see a reason to exclude yourself from this notification or any way this might cause issues for clients.
Note that the SASL 900 RPL_LOGGEDIN numeric might also be sent in this case, but isn't always in practice.
=> [account-notify] Send ACCOUNT to self as well

client-tags/typing.md
I tidied up the sections to more closely match other specs, pulled various things out into bullet points and removed sections that don't seem relevant.
---
Unchecked means incomplete or an intent to implement has been expressed. The numbers indicate minimum requirements. Any others?
Client tags don't require server support for ratification. Specific servers that filter client tags are listed here if they support (or will support) this spec
=> [typing] Clarify and ratify typing notifications

extensions/message-tags.md
This implements the consensus (afaict) from #410
It also makes the allowance for moderating tags less specific to TAGMSG.
=> [message-tags] CLIENTTAGDENY isupport token

client-tags/typing.md
`paused` is a value for +typing, like `active` and `done`. The value is *not* `typing-paused`.
=> [typing] Fix trivial typo

extensions/multiline.md
This addresses issues raised in https://github.com/oragono/oragono/issues/1005#issuecomment-628000227
* Clarify line feed joiner takes up one byte
* Servers MUST NOT reject blank lines (they can be used to create extra new lines)
* Clients MUST NOT send concat only blank lines or blank-only messages
* Servers MUST NOT send blank lines in legacy fallback (clients may well handle these but they're normally not allowed. An alternative may be to turn them into lines containing a single space, but not sure about that)
I don't think the suggestion to disallow a leading blank line is correct.
=> [multiline] Clarify blank line and line feed handling

extensions/chghost-3.2.md
This PR replaces and builds on #364, incorporating the latest suggestions around showing unidented tildes, and also moving the fallback description to its own subheading.
=> Clarify chghost

extensions/chathistory.md
Overhaul from previous CHATHISTORY spec https://github.com/ircv3/ircv3-specifications/pull/349
Creating a new PR since the majority of it has now changed and most previous comments are no longer relevant with these changes.
Changes:
* Explanation of each subcommand	
* Unified and simpler syntax for each subcommand	
* Removal of many ambiguities throughout the spec	
* Removal of conflicting command parameters	
* Removal of unrelated specs being mentioned in examples and notes
* Simplified and explicitly defined errors
=> Add the CHATHISTORY extension specification - refactored

core/capability-negotiation.md
Attempt to address #405
This version doesn't allow multiline LS replies to be sent to 301 clients. An alternative version that does might look like:
> Servers MAY send multiple lines in response to `CAP LS` and `CAP LIST` but SHOULD NOT send them to clients that do not support CAP version `302`. Clients that support CAP version `302` MUST and other clients SHOULD handle the continuation format described as follows:
But this seems odd. Why should 301 clients support this if servers shouldn't be sending it?
=> Clarify that multiline LS and LIST replies must only be used for CAP 302

extensions/chathistory.md
@kylef alerted me to the fact that Oragono violates a MUST of the current spec: "If the server receives a `CHATHISTORY` command with missing parameters, the `NEED_MORE_PARAMS` error code MUST be returned." Oragono will send `461 ERR_NEEDMOREPARAMS` in some cases, based on generic command-handling logic.
Upon consideration, there doesn't seem to be much of a point in having a MUST here at all, or in requiring distinct error codes for `UNKNOWN_COMMAND` and `NEED_MORE_PARAMS`: these are both programming errors, rather than runtime errors, and they're unrecoverable at runtime, so the only job of the error message is to illuminate the problem for debugging. Hence this proposed change does the following:
1. All FAIL codes are now SHOULD
2. All unrecoverable programming errors are now …
=> chathistory: soften FAIL code guarantees for programming errors

extensions/sts.md
Also clarify part requirements and connection types
This follows up from https://github.com/ircv3/ircv3-specifications/pull/390#issuecomment-785220509 and makes the requirements a bit clearer.
The goal here is to allow for potential policy extension in future without breaking existing implementations.
=> [sts] require clients to ignore missing policy parts.

extensions/bot-mode.md
This specification defines the Bot mode, ISUPPORT token and WHO flags which are already in use by a number of IRC servers. It also defines the `bot` tag, which is in use as a vendor tag by InspIRCd right now (as `inspircd.org/bot`).
Short, sweet, simple. Mostly explains existing behaviour apart from that `bot` tag, and I don't really feel like it's necessary to go through the whole `draft/` prefix for six months stage for something which is a simple tag like this.
Discussion happened in https://github.com/ircv3/ircv3-ideas/issues/43 and servers implemented and converged on this behaviour (apart from the tag) during that discussion.
=> Bot mode (+B)

extensions/utf8-only.md
The ISUPPORT token `UTF8ONLY` indicates "this server only accepts or relays UTF-8 content".
This is implemented (configurable, but a recommended default) in Oragono's master and the new [v2.5.0-rc1](https://github.com/oragono/oragono/releases/tag/v2.5.0-rc1) release candidate.
=> spec for UTF8ONLY

deprecated/tls.md
This fixes an error 404 on page tls, for the link "Strict Transport Security".
=> Fix broken link from deprecated tls extension to STS page

client-tags/typing.md
The old description was ambiguous, so this PR replaces it with the
most logical interpretation.
=> typing: Clarify when typing status is cleared

extensions/chathistory.md
This comes from discussion on #444 (cc @kylef, @emersion, @hhirtz). In short:
1. CHATHISTORY needs a way to surface DMs with previously unknown users. The previous proposal for this was the `*` target (which "contained" all DMs sent to or from the user).
2. Client developers don't like the `*` target; it has the problem that high-priority DMs from friends can get blocked behind spam
3. Bouncer developers don't like the `*` target; in a typical bouncer implementation, there is no global time index over all DMs (nor any need for one)
So, this proposal adds an explicit way to list DM correspondents, with pagination support, and removes the `*` target. It's marked as a draft; the intent is that Oragono 2.6.0 will include some version of this API, but will continue to include the `*` target …
=> CHATHISTORY TARGETS

extensions/sasl-3.1.md
This low-level grammar enforced a serialization stricter than usual
IRC commands; while most implementations use the latter (accepting,
and sometimes emitting extra colons), leading to misunderstandings.
Closes GH-467.
=> AUTHENTICATE: Use a higher-level grammar consistent with other IRCv3 specs

extensions/capability-negotiation.md
Closes #469 
Add sentence clarifying values are not to be sent via CAP DEL
=> Clarify only sending values with CAP LS and NEW

extensions/message-tags.md
I know it's somewhat trivial, and `<params>` (erroneously) is required in RFC1459, but I believe it shouldn't be.
RFC 1459 defines params as:
```ebnf
<params>   ::= <SPACE> [ ':' <trailing> | <middle> <params> ]
```
Which would meant at minimum, we would need to format a message like this
```ebnf
<command> <SPACE> <crlf>
```
I know that IRC doesn't require a space between `<command>` and `<crlf>` where there are no middle or trailing parameters, but that's what seems to be indicated.
It's also very possible I could be misreading this - I'm certainly not a Backus–Naur form expert.
=> Params should not be required

extensions/monitor.md
The word target is consistently applied to the nickname that is being monitored. In these lines, target is mainly used throughout the document (and even within the same sentence) to refer to the nickname of the person sending the monitor request, not who is being monitored. By simply using 'nick' instead of 'target' or 'target nick', this clarifies the who this refers to for a new developer.
=> remove confusing 'target' from 730/1

extensions/chathistory.md
Minor nitpick
"<key_name>      ::= <non-empty sequence of ascii letters, digits, hyphens ('-')>"
-- https://ircv3.net/specs/extensions/message-tags
=> chathistory: Replace invalid character in tag example

extensions/multi-prefix.md
This is a small errata to address an inconsistency in the `multi-prefix` specification. There are 3 commands which replies contain user prefixes: NAMES, WHO, WHOIS. WHOIS is currently not listed in the specification, which means that compliant servers should currently not send multiple user prefixes in reply to WHOIS in their RPL_WHOISCHANNELS.
I think that this is simply an oversight in the original spec, and that it makes sense that WHOIS replies should also have all the user prefixes.
Here's a table compiled from the [list of servers supporting multi-prefix](https://ircv3.net/software/servers), that shows whether they send a multi-prefix for WHOIS replies (currently *not* spec-compliant) or they don't (compliant, but not consistent with NAMES and WHO).
| IRCd | Sends multi-prefix for …
=> [multi-prefix] Add WHOIS to commands which replies contain all prefixes

extensions/webirc.md
Add option parameters to WEBIRC specification to allow forwarding of tls client certificate fingerprints through WebIRC gateways.
=> Add certfp and spkifp options to WEBIRC

extensions/account-registration.md, extensions/register.md
This draft specification adds **simple** `REGISTER` and `VERIFY` commands to standardize account creation, as a replacement for the withdrawn [Account Management Framework](https://github.com/ircv3/ircv3-specifications/pull/276)
It is based on @edk0's [draft](https://gist.github.com/edk0/bf3b50fc219fd1bed1aa15d98bfb6495), and is implemented by Oragono and Limnoria.
[rendered view](https://github.com/ProgVal/ircv3-specifications/blob/register/extensions/register.md)
=> Add draft account-registration spec

extensions/bot-mode.md
Unchecked means incomplete or an intent to implement has been expressed. The numbers indicate minimum requirements. Any others?
=> Ratify bot-mode

extensions/account-tag.md
Whilst it might be useful to have an account tag on server-originated numerics that relate to a specific user it seems that everyone who implemented account tag in a server missed this bit of the spec.
I'm planning on updating our implementation (which was written by someone else) to implement this but I suspect it might be difficult for some implementations to do and as 100% of the implementations in the wild don't implement it currently it can't be relied on.
Therefore, I propose that we weaken the MUST to a SHOULD.
=> Change the requirement to add an account tag to numerics to SHOULD.

extensions/extended-monitor.md
I don't think there are any objections relating to this and we have enough implementations so lets ratify and ship it!
---
Unchecked means incomplete or an intent to implement has been expressed. The numbers indicate minimum requirements. Any others?
=> Ratify the extended-monitor specification.

extensions/utf8-only.md
cc @DanielOaks @vanosg 
This is a response to the discussion on #456. It deletes the suggestion that servers disconnect noncompliant clients; this was unnecessarily controversial. Other language implying that UTF8 is now the preferred encoding for IRC remains in place.
Since there are no normative implications to this change (the server behavior remains implementation-defined; servers MAY still disconnect the client, although no server does so and I don't think any ever will), this shouldn't require an erratum notice.
=> UTF8ONLY: remove suggestion to disconnect the client

extensions/standard-replies.md
This capability allows clients to signal that they support receiving arbitrary standard replies that are not otherwise enabled by a specific specification.
InspIRCd has something similar to this as a vendor capability and I'm planning on switching all of our custom numerics and notices over to it in v4. It'd be nice if we could standardise it so clients don't have to rely on a proprietary feature.
=> Add a capability for sending arbitrary standard replies.

extensions/chathistory.md
It appears that both Soju and Matrix2051 have issues implementing one of the types (resp. msgid and timestamp).
While they could add full support eventually, these would cause higher resource usage, so it will be beneficial to indicate a preference even if both types are supported.
@emersion and I considered adding [optional `msgid`s to read-marker](https://github.com/ircv3/ircv3-specifications/compare/master...progval:ircv3-specifications:read-marker-msgreftype) but it would add a lot of complexity to clients, without much benefit.
=> chathistory: Add MSGREFTYPES ISUPPORT token

extensions/capability-negotiation.md
It's _implied_ that capability names shouldn't start with a `-`, but not explicitly specified. Capability names "MUST" be treated as opaque identifiers. However, any possibility of a capability name that starts with `-` at all introduces ambiguity at the parsing step, and disallows simple solutions like `if cap_name.startswith('-')` and `real_cap = cap_name.lstrip('-')`. This patch proposes a formal prohibition on `-` as the first character of a capability name.
None of the CAP names listed in [the IRCv3 registry](https://ircv3.net/registry#capabilities) have leading hyphens, nor have I ever seen a `draft/` or `vendor/` CAP name with one. The impact of this change on any live code should be nonexistent outside of (as a fellow developer put it) hypothetical "particularly antisocial" …
=> capability-negotiation: clarify CAP names cannot start with hyphen

extensions/pre-away.md
This comes out of https://github.com/ircv3/ircv3-ideas/issues/96 . It provides a mechanism to indicate that a new connection was not initiated by an end user and does not indicate that the end user is present. The core objective is to work with auto-away systems, but the mechanism is potentially more general.
=> add pre-away extension

extensions/multiline.md
This matches the behavior [in Ergo](https://github.com/ergochat/ergo/blob/4317016a09a2629603fb6198cbeddf6afa28c8ce/irc/handlers.go#L2163-L2170) and [in Limnoria](https://github.com/progval/limnoria/blob/96b7f51e7162f540475ed9dd8763dff38a256e64/src/callbacks.py#L927-L946).
[BitBot ignores `max-bytes`](https://github.com/bitbot-irc/bitbot/blob/4a6037c77405f3584efadc10ae75826b6b9ac422/modules/ircv3_multiline.py); and I did not check how the IRCCloud server implements it (though the client does not seem to enforce it at all before sending).
Resolves #516.
=> multiline: Clarify what counts toward max-bytes

extensions/away-notify.md
This matches every known server implementation (with the possible exceptions of IRCCloud Teams and txird, which I did not test).
=> away-notify: Clarify away notifications should not be echoed

extensions/capability-negotiation.md
UnrealIRCd and InspIRCd emit them.
=> capability-negotiation: Mention trailing space in capability lists

extensions/no-implicit-names.md
This has been deployed on soju and goguma.
See benchmarks in https://github.com/ircv3/ircv3-ideas/issues/87#issuecomment-1066766062.
Last week I was in the countryside with only 3G access and this was useful.
=> Add draft/no-implicit-names

extensions/message-redaction.md
[Rendered](https://github.com/progval/ircv3-specifications/blob/redaction/extensions/message-redaction.md)
This is https://github.com/ircv3/ircv3-specifications/pull/425 with the following changes:
* no edits, because it's way more complicated to handle them safely, so IMO it should be deferred to a future spec
* targetmsgid is moved to a param (instead of a tag, because it didn't really make sense with a dedicated verb)
* added an optional reason (just because I can)
* renamed "delete" to "redact" so the cap name doesn't conflict with the other one (and there is some argument esp. in Matrix circles that "redact" better reflects that it's best effort and other clients might not respect it, but I don't really buy it)
* explicitly gives a lot of freedom to servers wrt chathistory
* new …
=> Add message redaction

extensions/chathistory.md, extensions/message-redaction.md
=> chathistory: Specify that REDACT in chathistory does not depend on event-playback

extensions/extended-isupport.md
Proposal for https://github.com/ircv3/ircv3-ideas/issues/124
=> Add extended-isupport

extensions/metadata.md
These came out of my review of the initial metadata implementation in Ergo, contributed by @thatcher-gaming. They're more starting points for discussion than polished amendments. A brief summary:
* `before-connect` allows clients to modify both their metadata and their subscriptions during connection registration. For conventional IRC stacks without persistent clients, this makes perfect sense. For bouncers and implementations like Ergo with persistent clients, it makes sense to be able to modify subscriptions, but clients probably shouldn't be unilaterally pushing metadata updates on every reconnection, since they may overwrite more up-to-date metadata that was set from another client. This adds a new cap value key, `sub-before-connect`, that indicates that subscriptions are accepted …
=> updates to metadata spec
