extensions/sasl-3.2.md

Per this evening's discussion on `#ircv3`, we:
* document the reauthentication ability
* document the integration with `cap-notify`, and
* explicitly allow a server to disconnect a user for excessive SASL authentication failures
The latter is to clarify that it is allowed in case anyone was confused about that.
All of this closes #103.

sasl-3.2 updates per #103

---

extensions/cap-notify-3.2.md

this change implements the requested action in the #119 proposal.
closes #119

cap-notify changes for #119

---

specification/metadata-3.2.md

Other changes:
* Remove services section; services should be receiving `METADATA` commands anyhow and metadata should be implicitly persistent.
* Reword the daemon section to be more explicit.
* Miscellaneous formatting fixes for enhanced readability.

metadata-3.2: Major rework.

---

specification/metadata-3.2.md

This addresses a few issues which were noted just prior to the recent metadata-3.2 work being merged.

metadata-3.2: Fix up numerics, add visibility to notifications.

---

extensions/batch/chathistory-3.3.md

[Rendered view available here.](https://github.com/SaberUK/ircv3-specifications/blob/master+chathistory/extensions/batch/chathistory-3.3.md)

Add the CHATHISTORY batch type specification.

---

extensions/cap-notify-3.2.md

cap-notify: Clarify behaviour for implicit support

---

core/sts-3.3.md

This can replace the STS spec portions of #232.

STS: Improved sections for Client/Server/Security implementation considerations

---

extensions/sasl-3.1.md

sasl-3.1: Clarify when RPL_SASLMECHS is sent

---

extensions/echo-message-3.2.md

Mentions perceived latency and private message to self issues being addressed by labeled replies. See #162

Add a limitations section to echo-message

---

extensions/server-time-3.2.md

[server-time] Add a recommendation for echo-message and tidy up some language

---

core/sts-3.3.md

In response to https://github.com/ircv3/ircv3-specifications/pull/168#issuecomment-269911673

[sts] Clarify that disabling a policy with CAP DEL is invalid

---

extensions/labeled-response.md

labeled-response.md: typos

---

client-tags/typing.md

[Rendered view available here.](https://github.com/MuffinMedic/ircv3-specifications/blob/typing/client-tags/typing.md)
Split out from #319

Add the typing client-tag specification

---

extensions/labeled-response.md

This PR addresses the following issues and should be merged before #378 (ratification)
* #380 how far should we go for a 100% correct implementation?
* #379 what is a response?
* #382 set a maximum size limit

Label revisions

---

extensions/labeled-response.md

[labeled-response] Make batch a hard dependency

---

extensions/labeled-response.md

I accidentally closed #378, this is a PR to ratify labeled-response.

Ratify labeled-response

---

extensions/chathistory.md

Not for immediate merge: I was thinking this would serve to aggregate discussion on changes to the chathistory draft.

errata to the chathistory draft

---

extensions/extended-monitor.md

Closes: https://github.com/ircv3/ircv3-specifications/issues/79

Add extended-monitor spec

---

extensions/account-registration.md

Copy-pasted from what Ergo sends

account-registration: Add examples of the 'working' cases.

---

extensions/account-registration.md

From discussion on https://github.com/ircv3/ircv3-specifications/issues/479

add FAIL * ACCOUNT_REQUIRED to account-registration

---

extensions/message-tags.md

Some servers (Unreal) do perform validation.

Reword 'Security considerations' to be less misleading about validation

---

extensions/message-redaction.md

As suggested in https://github.com/ircv3/ircv3-specifications/issues/537#issuecomment-2051540328

Clarify paragraph about sending REDACT in on-JOIN chathistory batch

---

extensions/account-extban.md

I asked about this on IRC and people seemed in agreement that such an ISUPPORT token should exist.

Add draft account-extban spec

---

extensions/metadata.md

Remove draft/metadata-notify-2
